vivlas旗舰店
20881318702350000156_201901_账务明细_1.csv表写入成功，共写入5453行数据
20881318702350000156_201902_账务明细_1.csv表写入成功，共写入3082行数据
20881318702350000156_201903_账务明细_1.csv表写入成功，共写入7763行数据
20881318702350000156_201904_账务明细_1.csv表写入成功，共写入2590行数据
文件夹读取完成，共处理了4个文件~，共计18888行
==============Traceback (most recent call last):
  File "D:/wendang/Python_Tools/references/instances_01/AliPay2UCO.py", line 119, in insert_df_to_mysql
    self.cursor.executemany(insert_sql, child_rows)  # 数组中每一条数据来执行insert_sql
  File "F:\pro\Python\lib\site-packages\pymysql\cursors.py", line 179, in executemany
    self._get_db().encoding,
  File "F:\pro\Python\lib\site-packages\pymysql\cursors.py", line 206, in _do_execute_many
    rows += self.execute(sql + postfix)
  File "F:\pro\Python\lib\site-packages\pymysql\cursors.py", line 148, in execute
    result = self._query(query)
  File "F:\pro\Python\lib\site-packages\pymysql\cursors.py", line 310, in _query
    conn.query(q)
  File "F:\pro\Python\lib\site-packages\pymysql\connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "F:\pro\Python\lib\site-packages\pymysql\connections.py", line 775, in _read_query_result
    result.read()
  File "F:\pro\Python\lib\site-packages\pymysql\connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "F:\pro\Python\lib\site-packages\pymysql\connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "F:\pro\Python\lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "F:\pro\Python\lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1205, 'Lock wait timeout exceeded; try restarting transaction')
Traceback (most recent call last):
  File "D:/wendang/Python_Tools/references/instances_01/AliPay2UCO.py", line 119, in insert_df_to_mysql
    self.cursor.executemany(insert_sql, child_rows)  # 数组中每一条数据来执行insert_sql
  File "F:\pro\Python\lib\site-packages\pymysql\cursors.py", line 179, in executemany
    self._get_db().encoding,
  File "F:\pro\Python\lib\site-packages\pymysql\cursors.py", line 206, in _do_execute_many
    rows += self.execute(sql + postfix)
  File "F:\pro\Python\lib\site-packages\pymysql\cursors.py", line 148, in execute
    result = self._query(query)
  File "F:\pro\Python\lib\site-packages\pymysql\cursors.py", line 310, in _query
    conn.query(q)
  File "F:\pro\Python\lib\site-packages\pymysql\connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "F:\pro\Python\lib\site-packages\pymysql\connections.py", line 775, in _read_query_result
    result.read()
  File "F:\pro\Python\lib\site-packages\pymysql\connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "F:\pro\Python\lib\site-packages\pymysql\connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "F:\pro\Python\lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "F:\pro\Python\lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1205, 'Lock wait timeout exceeded; try restarting transaction')
